'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a basic mobile app from a natural language prompt.
 *
 * The flow takes a prompt describing the app's features, pages, and design, and returns a structured plan for the application code.
 * It exports the following:
 * - `generateAppFromPrompt`: The main function to trigger the app generation flow.
 * - `GenerateAppFromPromptInput`: The input type for the `generateAppFromPrompt` function.
 * - `GenerateAppFromPromptOutput`: The output type for the `generateAppFromPrompt` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema for the generateAppFromPrompt flow
const GenerateAppFromPromptInputSchema = z.object({
  prompt: z.string().describe('A natural language prompt describing the app features, pages, and design.'),
});

export type GenerateAppFromPromptInput = z.infer<typeof GenerateAppFromPromptInputSchema>;

// Define the output schema for the generateAppFromPrompt flow
const GenerateAppFromPromptOutputSchema = z.object({
  files: z.array(z.object({
    path: z.string().describe('The full path of the file to be created.'),
    content: z.string().describe('The code or content of the file.'),
  })).describe('A list of files to be generated for the app, including their paths and content.'),
});

export type GenerateAppFromPromptOutput = z.infer<typeof GenerateAppFromPromptOutputSchema>;

// Define the main function to trigger the app generation flow
export async function generateAppFromPrompt(input: GenerateAppFromPromptInput): Promise<GenerateAppFromPromptOutput> {
  return generateAppFromPromptFlow(input);
}

// Define the prompt for generating the app
const generateAppPrompt = ai.definePrompt({
  name: 'generateAppPrompt',
  input: {schema: GenerateAppFromPromptInputSchema},
  output: {schema: GenerateAppFromPromptOutputSchema},
  prompt: `You are an AI app generator. Please generate a basic Flutter application based on the following prompt: {{{prompt}}}.

  Your output should be a structured list of files, including their paths and content, that represents a standard Flutter project structure.
  
  Create a simple multi-page Flutter app with navigation. Ensure the file structure is correct.

  Provide the content for the following files at minimum:
  - pubspec.yaml
  - analysis_options.yaml
  - lib/main.dart
  - lib/home_page.dart
  - lib/details_page.dart
  - test/widget_test.dart
  - android/app/build.gradle (a minimal version)
  - ios/Runner/Info.plist (a minimal version)
  
  For directories like 'assets', 'web', 'android', 'ios', you can create placeholder files like '.gitkeep' if the full content is not necessary.

  The code should be complete, correct, and ready to be written to files.
  `,
});

// Define the Genkit flow for generating the app from the prompt
const generateAppFromPromptFlow = ai.defineFlow(
  {
    name: 'generateAppFromPromptFlow',
    inputSchema: GenerateAppFromPromptInputSchema,
    outputSchema: GenerateAppFromPromptOutputSchema,
  },
  async input => {
    const {output} = await generateAppPrompt(input);
    
    // For now, if the output is empty, return a placeholder file structure.
    // This can be removed once the model reliably returns the file list.
    if (!output || !output.files || output.files.length === 0) {
      return {
        files: [
          {
            path: 'pubspec.yaml',
            content: `
name: genius_appio_generated_app
description: A new Flutter project generated by Genius APPio.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
            `.trim(),
          },
           {
            path: 'analysis_options.yaml',
            content: `
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
            `.trim(),
          },
          {
            path: 'lib/main.dart',
            content: `
import 'package:flutter/material.dart';
import 'package:genius_appio_generated_app/home_page.dart';
import 'package:genius_appio_generated_app/details_page.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Genius APPio Generated App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const HomePage(),
        '/details': (context) => const DetailsPage(),
      }
    );
  }
}
            `.trim(),
          },
           {
            path: 'lib/home_page.dart',
            content: `
import 'package:flutter/material.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Welcome to your generated app!',
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              child: const Text('Go to Details'),
              onPressed: () {
                Navigator.pushNamed(context, '/details');
              },
            ),
          ],
        ),
      ),
    );
  }
}
            `.trim(),
          },
          {
            path: 'lib/details_page.dart',
            content: `
import 'package:flutter/material.dart';

class DetailsPage extends StatelessWidget {
  const DetailsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Details'),
      ),
      body: const Center(
        child: Text('This is the details page.'),
      ),
    );
  }
}
            `.trim(),
          },
          {
            path: 'test/widget_test.dart',
            content: `
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:genius_appio_generated_app/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(const MyApp());

    // Verify that our counter starts at 0.
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    // Tap the '+' icon and trigger a frame.
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    // Verify that our counter has incremented.
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}
            `.trim(),
          },
          {
            path: 'android/.gitkeep',
            content: '',
          },
          {
            path: 'ios/.gitkeep',
            content: '',
          },
           {
            path: 'assets/.gitkeep',
            content: '',
          },
           {
            path: 'web/.gitkeep',
            content: '',
          },
        ]
      };
    }
    
    // Add package name to dart files
    output.files.forEach(file => {
      if (file.path.startsWith('lib/')) {
        file.content = file.content.replace(/import '(.+?)';/g, (match, p1) => {
          if (p1.startsWith('package:')) return match;
          return `import 'package:genius_appio_generated_app/${p1}';`;
        });
      }
    });

    return output!;
  }
);
