
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a basic mobile app from a natural language prompt.
 *
 * The flow takes a prompt describing the app's features, pages, and design, and returns a structured plan for the application code.
 * It exports the following:
 * - `generateAppFromPrompt`: The main function to trigger the app generation flow.
 * - `GenerateAppFromPromptInput`: The input type for the `generateAppFromPrompt` function.
 * - `GenerateAppFromPromptOutput`: The output type for the `generateAppFromPrompt` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema for the generateAppFromPrompt flow
const GenerateAppFromPromptInputSchema = z.object({
  prompt: z.string().describe('A natural language prompt describing the app features, pages, and design.'),
});

export type GenerateAppFromPromptInput = z.infer<typeof GenerateAppFromPromptInputSchema>;

// Define the output schema for the generateAppFromPrompt flow
const GenerateAppFromPromptOutputSchema = z.object({
  files: z.array(z.object({
    path: z.string().describe('The full path of the file to be created.'),
    content: z.string().describe('The code or content of the file.'),
  })).describe('A list of files to be generated for the app, including their paths and content.'),
});

export type GenerateAppFromPromptOutput = z.infer<typeof GenerateAppFromPromptOutputSchema>;

// Define the main function to trigger the app generation flow
export async function generateAppFromPrompt(input: GenerateAppFromPromptInput): Promise<GenerateAppFromPromptOutput> {
  return generateAppFromPromptFlow(input);
}

// Define the prompt for generating the app
const generateAppPrompt = ai.definePrompt({
  name: 'generateAppPrompt',
  input: {schema: GenerateAppFromPromptInputSchema},
  output: {schema: GenerateAppFromPromptOutputSchema},
  prompt: `You are an expert Flutter app generator. Your task is to take a user's prompt and generate a complete, structured, and functional Flutter project from it.

  **Process:**

  1.  **Parse the Prompt:** First, analyze the user's prompt and extract the core components into a structured JSON format. This should include:
      *   \`appName\`: The name of the application.
      *   \`screens\`: A list of the required screens/pages.
      *   \`features\`: A list of key features (e.g., Authentication, ThemeSwitch, StoryGeneration).

  2.  **Generate the File Structure:** Based on the parsed JSON, generate the complete file structure for a standard Flutter project.

  **User Prompt:**
  "{{{prompt}}}"

  **Output Requirements:**

  *   The output MUST be a JSON object conforming to the output schema.
  *   The \`files\` array should represent a complete Flutter project structure.
  *   Provide content for all essential files, including:
      *   \`pubspec.yaml\` (with necessary dependencies like cupertino_icons, and others if needed).
      *   \`analysis_options.yaml\`
      *   \`lib/main.dart\` (including theme data, and routes for all generated screens).
      *   \`lib/screens/\` (a separate .dart file for each screen identified).
      *   \`lib/widgets/\` (if any reusable widgets are created).
      *   \`lib/services/\` (if any services like authentication are needed).
      *   \`README.md\` (a basic readme).
      *   Placeholder files (\`.gitkeep\`) for empty directories like \`assets\`, \`android\`, \`ios\`, \`web\`, \`test\`.
  
  *   The generated Dart code should be clean, correct, and use modern Flutter practices.
  *   The package name in all Dart files should be derived from the app name (e.g., 'ai_story_gen'). Replace spaces with underscores.
  `,
});

// Define the Genkit flow for generating the app from the prompt
const generateAppFromPromptFlow = ai.defineFlow(
  {
    name: 'generateAppFromPromptFlow',
    inputSchema: GenerateAppFromPromptInputSchema,
    outputSchema: GenerateAppFromPromptOutputSchema,
  },
  async input => {
    const {output} = await generateAppPrompt(input);
    
    if (!output || !output.files || output.files.length === 0) {
      // Fallback to a default project structure if the AI fails.
      const appName = "my_awesome_app";
      return {
        files: [
          {
            path: 'pubspec.yaml',
            content: `
name: ${appName}
description: A new Flutter project generated by Genius APPio.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
            `.trim(),
          },
           {
            path: 'analysis_options.yaml',
            content: `
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
            `.trim(),
          },
          {
            path: 'lib/main.dart',
            content: `
import 'package:flutter/material.dart';
import 'package:my_awesome_app/screens/home_screen.dart';
import 'package:my_awesome_app/screens/details_screen.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Generated App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const HomeScreen(),
        '/details': (context) => const DetailsScreen(),
      }
    );
  }
}
            `.trim(),
          },
           {
            path: 'lib/screens/home_screen.dart',
            content: `
import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Welcome to your generated app!',
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              child: const Text('Go to Details'),
              onPressed: () {
                Navigator.pushNamed(context, '/details');
              },
            ),
          ],
        ),
      ),
    );
  }
}
            `.trim(),
          },
          {
            path: 'lib/screens/details_screen.dart',
            content: `
import 'package:flutter/material.dart';

class DetailsScreen extends StatelessWidget {
  const DetailsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Details'),
      ),
      body: const Center(
        child: Text('This is the details page.'),
      ),
    );
  }
}
            `.trim(),
          },
          { path: 'README.md', content: '# My Awesome App\n\nGenerated by Genius APPio.' },
          { path: 'android/.gitkeep', content: '' },
          { path: 'ios/.gitkeep', content: '' },
          { path: 'assets/.gitkeep', content: '' },
          { path: 'web/.gitkeep', content: '' },
          { path: 'test/.gitkeep', content: '' },
        ]
      };
    }

    return output;
  }
);

    